import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApp } from '../server/app.mjs';
import { request as httpRequest } from 'node:http';

test('HTTP commands, independent SSE clients, reconnect, and static routes', async t => {
  const app = await createApp({ dataDir: await mkdtemp(join(tmpdir(), 'stream-polls-http-')) });
  const url = await app.listen(0);
  t.after(() => app.close());
  const request = (body, headers = {}) => fetch(url + '/api/command', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Poll-Client': 'panel', ...headers }, body: JSON.stringify(body) });
  for (const path of ['/', '/overlay', '/shared.js', '/style.css', '/fonts/geist-cyrillic.woff2', '/fonts/geist-latin.woff2']) assert.equal((await fetch(url + path)).status, 200);
  const panelHtml = await (await fetch(url + '/')).text();
  const assets = [...panelHtml.matchAll(/(?:src|href)="(\/assets\/[^"]+)"/g)].map(match => match[1]);
  assert.equal(assets.length, 2);
  for (const asset of assets) assert.equal((await fetch(url + asset)).status, 200);
  assert.equal((await fetch(url + '/data/state.json')).status, 404);
  assert.equal((await request({ type: 'tick' }, { Origin: 'https://example.com' })).status, 403);
  const invalidHost = await new Promise((resolve, reject) => {
    const req = httpRequest(url + '/api/state', { headers: { Host: 'attacker.example' } }, res => { res.resume(); resolve(res.statusCode); });
    req.on('error', reject); req.end();
  });
  assert.equal(invalidHost, 403);
  assert.equal((await fetch(url + '/api/command', { method: 'POST', body: '{}' })).status, 415);
  const abort = new AbortController();
  const response = await fetch(url + '/api/events', { signal: abort.signal });
  assert.match(response.headers.get('content-type'), /text\/event-stream/);
  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  const first = decoder.decode((await reader.read()).value);
  assert.match(first, /event: state/);
  const initial = await (await fetch(url + '/api/state')).json();
  const started = await (await request({ type: 'start', draftRevision: 0, draft: initial.draft })).json();
  const event = decoder.decode((await reader.read()).value);
  assert.match(event, /"status":"running"/);
  const result = await (await request({ type: 'vote', pollId: started.state.poll.id, viewerId: 'demo-a', eventId: 'a', message: 'майн' })).json();
  assert.equal(result.state.poll.options[0].votes, 1);
  abort.abort();
  const reconnect = new AbortController();
  const stream = await fetch(url + '/api/events', { signal: reconnect.signal });
  const restored = decoder.decode((await stream.body.getReader().read()).value);
  assert.match(restored, /"votes":1/);
  reconnect.abort();
  assert.equal((await request({ type: 'unknown' })).status, 400);
  assert.equal((await fetch(url + '/api/twitch')).status, 200);
  assert.equal((await fetch(url + '/data/twitch.json')).status, 404);
  assert.equal((await fetch(url + '/api/twitch', { method: 'POST', body: '{}' })).status, 415);
  assert.equal((await request({ type: 'start', draftRevision: result.state.draftRevision, draft: { ...initial.draft, source: 'twitch' } })).status, 409);
  await app.store.command({ type: 'finish', pollId: started.state.poll.id });
  const live = await app.store.command({ type: 'start', draftRevision: result.state.draftRevision, broadcasterId: '123', draft: { ...initial.draft, source: 'twitch', showOverlay: false } });
  const injected = await (await request({ type: 'vote', source: 'twitch', broadcasterId: '123', sentAt: Date.now(), pollId: live.state.poll.id, viewerId: 'fake', eventId: 'fake', message: 'майн' })).json();
  assert.equal(injected.outcome, 'wrong-source');
  assert.equal(injected.state.poll.options[0].votes, 0);
});
